all: padreFiglioConStatus padreSenzaFigli padreFiglioConStatus1 provaWait padreFigliMultipli padreFigliConSalvataggioPID padreFigliConConteggioOccorrenze
padreFigliConSalvataggioPID: padreFigliConSalvataggioPID.c
	gcc -Wall -std=c11 -o padreFigliConSalvataggioPID padreFigliConSalvataggioPID.c
provaWait: provaWait.c
	gcc -Wall -std=c11 -o provaWait provaWait.c
padreFiglioConStatus: padreFiglioConStatus.c
	gcc -Wall -std=c11 -o padreFiglioConStatus padreFiglioConStatus.c
padreSenzaFigli: padreSenzaFigli.c
	gcc -Wall -std=c11 -o padreSenzaFigli padreSenzaFigli.c
padreFiglioConStatus1: padreFiglioConStatus1.c
	gcc -Wall -std=c11 -o padreFiglioConStatus1 padreFiglioConStatus1.c
padreFigliMultipli: padreFigliMultipli.c
	gcc -Wall -std=c11 -o padreFigliMultipli padreFigliMultipli.c
padreFigliConConteggioOccorrenze: padreFigliConConteggioOccorrenze.c
	gcc -Wall -std=c11 -o padreFigliConConteggioOccorrenze padreFigliConConteggioOccorrenze.c