all: prova mylsConFork1 myGrepConFork-ridStError myGrepConFork-ridStErrorEInput mycat myCatConFork padreFigliNipotiConExec

myCatConFork: myCatConFork.c
	gcc -Wall -std=c11 -o myCatConFork myCatConFork.c

myGrepConFork-ridStError: myGrepConFork-ridStError.c
	gcc -Wall -std=c11 -o myGrepConFork-ridStError myGrepConFork-ridStError.c

mylsConFork1: mylsConFork1.c
	gcc -Wall -std=c11 -o mylsConFork1 mylsConFork1.c

prova: prova.c
	gcc -Wall -std=c11 -o prova prova.c

myGrepConFork-ridStErrorEInput: myGrepConFork-ridStErrorEInput.c
		gcc -Wall -std=c11 -o myGrepConFork-ridStErrorEInput myGrepConFork-ridStErrorEInput.c

padreFigliNipotiConExec: padreFigliNipotiConExec.c
	gcc -Wall -std=c11 -o padreFigliNipotiConExec padreFigliNipotiConExec.c