all: provaPipe-Bis pipe-SenzaClose pipe-Generico1 pipe-Generico2 provaEsame1 provaEsame2-a provaEsame2-b provaEsame2-b2

provaEsame2-b: provaEsame2-b.c
	gcc -Wall -std=c11 -o provaEsame2-b provaEsame2-b.c
provaEsame2-a: provaEsame2-a.c
	gcc -Wall -std=c11 -o provaEsame2-a provaEsame2-a.c

provaEsame1: provaEsame1.c
	gcc -Wall -std=c11 -o provaEsame1 provaEsame1.c

pipe-Generico2: pipe-Generico2.c
	gcc -Wall -std=c11 -o pipe-Generico2 pipe-Generico2.c
pipe-Generico1: pipe-Generico1.c
	gcc -Wall -std=c11 -o pipe-Generico1 pipe-Generico1.c

pipe-SenzaClose: pipe-SenzaClose.c
	gcc -Wall -std=c11 -o pipe-SenzaClose pipe-SenzaClose.c

provaPipe-Bis: provaPipe-Bis.c
	gcc -Wall -std=c11 -o provaPipe-Bis provaPipe-Bis.c

provaEsame2-b2: provaEsame2-b2.c
	gcc -Wall -std=c11 -o provaEsame2-b2 provaEsame2-b2.c