all: parametri1 parametri2 provaBUFSIZ contaOccorenze

contaOccorenze: contaOccorenze.c
	gcc -Wall -std=c11 -o contaOccorenze contaOccorenze.c

parametri2: parametri2.c
	gcc -Wall -std=c11 -o parametri2 parametri2.c

parametri1: parametri1.c
	gcc -Wall -std=c11 -o parametri1 parametri1.c

provaBUFSIZ: provaBUFSIZ
	gcc -Wall -std=c11 -o provaBUFSIZ provaBUFSIZ.c

