all: parametri1 parametri2 provaBUFSIZ contaOccorenze myCat selezionaMultipli1 selezionaMultipli2 sostituisciCar sostituisciCar1 myhead1 myhead2 myhead3 selezionaLungezzaLinea

selezionaLungezzaLinea: selezionaLungezzaLinea.c
	gcc -Wall -std=c11 -o selezionaLungezzaLinea selezionaLungezzaLinea.c

selezionaLinea: selezionaLinea.c
	gcc -Wall -std=c11 -o selezionaLinea selezionaLinea.c

myhead3: myhead3.c
	gcc -Wall -std=c11 -o myhead3 myhead3.c

myhead2: myhead2.c
	gcc -Wall -std=c11 -o myhead2 myhead2.c

myhead1: myhead1.c
	gcc -Wall -std=c11 -o myhead1 myhead1.c

sostituisciCar1: sostituisciCar1.c
	gcc -Wall -std=c11 -o sostituisciCar1 sostituisciCar1.c

sostituisciCar: sostituisciCar.c
	gcc -Wall -std=c11 -o sostituisciCar sostituisciCar.c

selezionaMultipli2: selezionaMultipli2.c
	gcc -Wall -std=c11 -o selezionaMultipli2 selezionaMultipli2.c

selezionaMultipli: selezionaMultipli1.c
	gcc -Wall -std=c11 -o selezionaMultipli1 selezionaMultipli1.c

myCat: myCat.c
	gcc -Wall -std=c11 -o myCat myCat.c

contaOccorenze: contaOccorenze.c
	gcc -Wall -std=c11 -o contaOccorenze contaOccorenze.c

parametri2: parametri2.c
	gcc -Wall -std=c11 -o parametri2 parametri2.c

parametri1: parametri1.c	
	gcc -Wall -std=c11 -o parametri1 parametri1.c

provaBUFSIZ: provaBUFSIZ
	gcc -Wall -std=c11 -o provaBUFSIZ provaBUFSIZ.c

